version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: compose
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: programbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: programbook123!
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"  # 내부용

volumes:
  db_data:
